name: Deploy to GitHub Pages

"on":
  push:
    branches: ['*']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Enable Pages
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAGES_TOKEN || secrets.GITHUB_TOKEN }}
          script: |
            try {
              await github.rest.repos.getPages({
                owner: context.repo.owner,
                repo: context.repo.repo
              });
            } catch (error) {
              if (error.status === 404) {
                await github.rest.repos.createPagesSite({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  build_type: "workflow",
                  source: { branch: "main", path: "/" }
                });
              }
            }

      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
